-- MySQL dump template for student_db
-- Schema only (data generated by generate_data.py)
-- Usage:
--   mysql -u root -p < db/students_db.sql
--   python db/generate_data.py | mysql -u root -p student_db

CREATE DATABASE IF NOT EXISTS `student_db` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci;
USE `student_db`;

-- -------------------------------------------
-- classes 班级表
-- -------------------------------------------
DROP TABLE IF EXISTS `classes`;
CREATE TABLE `classes` (
    `class_id`   INT         NOT NULL AUTO_INCREMENT,
    `class_name` VARCHAR(50) NOT NULL,
    PRIMARY KEY (`class_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- -------------------------------------------
-- students 学生表
-- -------------------------------------------
DROP TABLE IF EXISTS `students`;
CREATE TABLE `students` (
    `id`         INT          NOT NULL AUTO_INCREMENT,
    `student_id` VARCHAR(50)  NOT NULL,
    `name`       VARCHAR(100) NOT NULL,
    `password`   VARCHAR(100) NOT NULL,
    `class_id`   INT          NOT NULL,
    PRIMARY KEY (`id`),
    UNIQUE KEY `student_id` (`student_id`),
    KEY `class_id` (`class_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- -------------------------------------------
-- scores 成绩表
-- -------------------------------------------
DROP TABLE IF EXISTS `scores`;
CREATE TABLE `scores` (
    `id`         INT           NOT NULL AUTO_INCREMENT,
    `student_id` VARCHAR(50)   NOT NULL,
    `subject`    VARCHAR(100)  NOT NULL,
    `type`       VARCHAR(50)   NOT NULL COMMENT 'monthly1|monthly2|midterm|final',
    `score`      DECIMAL(5,1)  NOT NULL,
    `exam_date`  DATE          NOT NULL COMMENT '考试日期，用于区分同类型的多次考试',
    PRIMARY KEY (`id`),
    KEY `student_id` (`student_id`),
    KEY `type_date` (`student_id`, `type`, `exam_date`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- -------------------------------------------
-- teachers 老师表
-- -------------------------------------------
DROP TABLE IF EXISTS `teachers`;
CREATE TABLE `teachers` (
    `teacher_id`   INT          NOT NULL AUTO_INCREMENT,
    `teacher_name` VARCHAR(100) NOT NULL,
    `subject`      VARCHAR(100) NOT NULL,
    `username`     VARCHAR(50)  NOT NULL,
    `password`     VARCHAR(100) NOT NULL,
    PRIMARY KEY (`teacher_id`),
    UNIQUE KEY `username` (`username`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- -------------------------------------------
-- teacher_class 老师-班级 多对多关系
-- -------------------------------------------
DROP TABLE IF EXISTS `teacher_class`;
CREATE TABLE `teacher_class` (
    `teacher_id` INT NOT NULL,
    `class_id`   INT NOT NULL,
    PRIMARY KEY (`teacher_id`, `class_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- -------------------------------------------
-- admins 管理员表
-- -------------------------------------------
DROP TABLE IF EXISTS `admins`;
CREATE TABLE `admins` (
    `id`       INT          NOT NULL AUTO_INCREMENT,
    `username` VARCHAR(50)  NOT NULL,
    `password` VARCHAR(100) NOT NULL,
    `name`     VARCHAR(100) NOT NULL,
    PRIMARY KEY (`id`),
    UNIQUE KEY `username` (`username`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;